optimized:
	hipcc -o matrix_sums_optimized matrix_sums_optimized.cpp

unoptimized:
	hipcc -o matrix_sums_unoptimized matrix_sums_unoptimized.cpp

clean:
	rm -f matrix_sums_optimized matrix_sums_unoptimized
