#!/bin/bash

#BSUB -P TRN019
#BSUB -J profiling_unoptimized
#BSUB -o profiling_output_unoptimized.%J
#BSUB -nnodes 1
#BSUB -W 15

module purge
module reset
module load gcc
module load cuda
module load nsight-systems

date

cp ./matrix_sums_unoptimized /gpfs/wolf/trn019/scratch/${USER}
cd /gpfs/wolf/trn019/scratch/${USER}

jsrun -n1 -c1 -g1 -a1 nsys profile --stats=true --force-overwrite=true -o profile_data_unoptimized ./matrix_sums_unoptimized

cp profil* $LS_SUBCWD
